#https://docs.astral.sh/ruff/settings/#lint_pylint_max-branches
# Lint/Formatter非依存のルール
# 除外したいファイル
# excludeを設定するとデフォルトで設定されている.venv配下などの設定が上書きされるため要注意
extend-exclude = ["tests","scripts",".venv","mlruns","result]
# 行文字数
line-length = 110
# インデント幅
indent-width = 4

target-version = "py310"
# Linterのルール
[lint]
# Lintルール
ignore = ["D", "ANN", "ERA001", "T201", "FBT003", "G004", "PLR0913", "RUF100", "E741"]
select = ["ALL"]

# https://docs.astral.sh/ruff/rules/　に記載されているルールのうち、Codeが前方一致するルールが適用されます
# 除外するLintルール
# print (T201): printがあると警告を出す
# commented-out-code (ERA001)
# flake8-annotations (ANN): アノテーション全般
# pydocstyle (D): docstring 全般
# boolean-positional-value-in-call (FBT003)
# logging-f-string (G004)
# too-many-arguments (PLR0913)
# unused-noqa (RUF100)
# ambiguous-variable-name (E741)
# selectで選択したルールから除外したいものを指定できます


# auto fixの対象にするルール
fixable = ["ALL"]
# auto fixから除外するルール
# editor.formatOnSaveを使う際に自動でFixされると困るものを指定できます
unfixable = ["F401"]

[lint.pylint]
#Maximum number of arguments allowed for a function or method definition (see: PLR0913).
max-args = 5

[lint.pydocstyle]
# Use numpy-style docstrings.
convention = "numpy"


# Formatterのルール
[format]

docstring-code-line-length = 60
# 文字列をダブルクォートに統一
quote-style = "double"
# インデントをタブ文字(\t)からスペースに変換
indent-style = "space"
skip-magic-trailing-comma = false # list等の最後の要素の後のコンマを削除しない。
